In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('play_tennis.csv')
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [3]:
data.drop(columns=['day'],inplace=True)

In [4]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [5]:
# Problem 1

# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
# Play or No Play?

In [6]:
# Solution

# P(Yes | Sunny,Hot,High,Weak) = P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes) * P(Yes)

# P(No | Sunny,Hot,High,Weak) = P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No) * P(No)

# Compare and decide using the Maximum a posteriori rule

In [7]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [8]:
py=9/14
pn=5/14

In [9]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [10]:
#outlook
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [11]:
Pon=0
Prn=2/5
Psn=3/5

Poy=4/9
Pry=3/9
Psy=2/9

In [12]:
#temp
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [13]:
PCoolNo=1/5
PHotNo=2/5
PMildNo=2/5

PCoolYes=3/9
PHotYes=2/9
PMildYes=4/9

In [14]:
#Humidity
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [15]:
PHighNo=4/5
PNormalNo=1/5

PHighYes=3/9
PNormalYes=6/9

In [16]:
#wind
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [17]:
PStrongNo=3/5
PWeakNo=2/5

PStrongYes=3/9
PWeakYes=6/9

In [18]:
# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak

Pyes=py*Psy*PHotYes*PHighYes*PWeakYes
print(Pyes)

0.007054673721340388

In [19]:
Pno=pn*Psn*PHotNo*PHighNo*PWeakNo
print(Pno)

0.02742857142857143

In [20]:
# Compare P(Yes|X) and P(No|X) -> Maximum a posteriori rule

if Pyes > Pno:
    print("Play = Yes")
else:
    print("Play = No")

Play = No

In [21]:
# Problem 2

# Outlook=Overcast, Temp=Cold, Humidity=Low, Wind=Weak
# Play or No Play?

In [22]:
# Solution

# P(Yes | Overcast,Cold,Low,Weak) = P(Overcast | Yes) * P(Cold | Yes) * P(Low | Yes) * P(Weak | Yes) * P(Yes)

# P(No | Overcast,Cold,Low,Weak) = P(Overcast | No) * P(Cold | No) * P(Low | No) * P(Weak | No) * P(No)

# Compare and decide using the Maximum a posteriori rule

In [23]:
# Note: this dataset only has Temp = {Hot, Mild, Cool} and Humidity = {High, Normal}.
# 'Cold' and 'Low' are not categories in this dataset, so they are treated here as
# Cool and Normal respectively (closest matching categories).

Pyes2=py*Poy*PCoolYes*PNormalYes*PWeakYes
print(Pyes2)

0.042328042328042326

In [24]:
Pno2=pn*Pon*PCoolNo*PNormalNo*PWeakNo
print(Pno2)

0.0

In [25]:
# Compare P(Yes|X) and P(No|X) -> Maximum a posteriori rule

if Pyes2 > Pno2:
    print("Play = Yes")
else:
    print("Play = No")

Play = Yes